<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQqUzDTD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQqUzDTD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQqUzDTD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQqUzDTD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQqUzDTD\App_KernelDevDebugContainer([
    'container.build_hash' => 'QqUzDTD',
    'container.build_id' => '5ce3933d',
    'container.build_time' => 1639866410,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQqUzDTD');
